<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" name="SciPassTest.TestInit-20151020154527" tests="2" time="0.004">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SciPassTest.TestInit" name="test_switch_init" time="0.003">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 41, in test_switch_init
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestInit" name="test_valid_config" time="0.002">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 21, in test_valid_config
    config = str(os.getcwd()) + "/t/etc/SciPass.xml"
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
</testsuite>
