<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" name="SciPassTest.TestInit-20150929153202" tests="2" time="0.004">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SciPassTest.TestInit" name="test_switch_init" time="0.002">
		<error message="'balancer'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 41, in test_switch_init
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 50, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 514, in _processConfig
    config[dpid][name]['balancer'].addSensorGroup(group_info)
KeyError: 'balancer'
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestInit" name="test_valid_config" time="0.001">
		<error message="'balancer'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 21, in test_valid_config
    config = str(os.getcwd()) + "/t/etc/SciPass.xml"
  File "./SciPass.py", line 50, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 514, in _processConfig
    config[dpid][name]['balancer'].addSensorGroup(group_info)
KeyError: 'balancer'
]]>		</error>
	</testcase>
</testsuite>
