<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20151020184042" tests="1" time="1.691">
	<properties/>
	<system-out>
<![CDATA[1000
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="1.691">
		<failure message="1000 != 566" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 42, in testInit
    self.assertEquals(len(flows), 566)
AssertionError: 1000 != 566

Stdout:
1000
]]>		</failure>
	</testcase>
</testsuite>
