<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="ConfigTest.TestPrefix-20150930183302" tests="2" time="2.013">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_prefx_split" time="2.007"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.005">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 46, in test_initial_config
    assert(prefix in ["10.0.17.0/24","10.0.18.0/24","10.0.19.0/24","10.0.20.0/24","::/128"])
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
