<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="BalancerOnlyTest.BalancerInitTest-20151021143547" tests="1" time="1.598">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="BalancerOnlyTest.BalancerInitTest" name="testBalance" time="1.598">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/BalancerOnlyTest.py", line 274, in testBalance
    self.assertTrue( len(flows) == 1132)
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
