<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930145201" tests="1" time="0.018">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initail_config" time="0.018">
		<error message="[Errno 2] No such file or directory: '0000000000000001R&amp;E'" type="IOError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 28, in test_initail_config
    with open(self.file) as data_file:
IOError: [Errno 2] No such file or directory: '0000000000000001R&E'
]]>		</error>
	</testcase>
</testsuite>
