<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930173232" tests="2" time="0.046">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.022"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_prefx_split" time="0.024">
		<error message="'TestPrefix' object has no attribute 'self'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 55, in test_prefx_split
    prefixList = self.self.api.getBalancer("%016x" % datapath.id, "R&E").splitPrefixForSensors(net,4)
AttributeError: 'TestPrefix' object has no attribute 'self'
]]>		</error>
	</testcase>
</testsuite>
