<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="BalancerOnlyTest.BalancerInitTest-20151020203931" tests="1" time="1.552">
	<properties/>
	<system-out>
<![CDATA[{'hard_timeout': 0, 'actions': [], 'priority': 65535, 'header': {'phys_port': 10, 'nw_src_mask': 32, 'nw_dst_mask': 32, 'nw_dst': 134744072, 'tp_dst': 2, 'tp_src': 1, 'nw_src': 167777282}, 'idle_timeout': '90', 'command': 'ADD', 'dpid': '0000000000000001'}
{'hard_timeout': 0, 'actions': [], 'priority': 65535, 'header': {'phys_port': 9}, 'idle_timeout': '90', 'command': 'ADD', 'dpid': '0000000000000001'}
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="BalancerOnlyTest.BalancerInitTest" name="test_bad_flow" time="1.552">
		<failure message="{'phys_port': 9} != {'phys_port': 9, 'nw_src_mask': 32, 'nw_dst_mask': 32, 'nw_dst': 167777282, 'tp_dst': 2, 'tp_src': 1, 'nw_src': 134744072}" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/BalancerOnlyTest.py", line 59, in test_bad_flow
    self.assertEqual(flow['header'],{'phys_port': 9, 'nw_src_mask': 32, 'nw_dst_mask': 32, 'nw_src': 134744072, 'tp_dst': 2, 'tp_src': 1, 'nw_dst': 167777282})
AssertionError: {'phys_port': 9} != {'phys_port': 9, 'nw_src_mask': 32, 'nw_dst_mask': 32, 'nw_dst': 167777282, 'tp_dst': 2, 'tp_src': 1, 'nw_src': 134744072}

Stdout:
{'hard_timeout': 0, 'actions': [], 'priority': 65535, 'header': {'phys_port': 10, 'nw_src_mask': 32, 'nw_dst_mask': 32, 'nw_dst': 134744072, 'tp_dst': 2, 'tp_src': 1, 'nw_src': 167777282}, 'idle_timeout': '90', 'command': 'ADD', 'dpid': '0000000000000001'}
{'hard_timeout': 0, 'actions': [], 'priority': 65535, 'header': {'phys_port': 9}, 'idle_timeout': '90', 'command': 'ADD', 'dpid': '0000000000000001'}
]]>		</failure>
	</testcase>
</testsuite>
