<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930142249" tests="1" time="0.019">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_split_prefix_for_sensors" time="0.019">
		<error message="SciPass instance has no attribute 'Balancer'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 44, in setUp
    res = self.api.Balancer("%016x" % datapath.id, "R&E").addSensorGroup({"group_id": 1,
AttributeError: SciPass instance has no attribute 'Balancer'
]]>		</error>
	</testcase>
</testsuite>
