<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20150929153125" tests="2" time="0.003">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="0.001">
		<error message="'balancer'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/Simple_SciPass_balancer_only.xml" )
  File "./SciPass.py", line 50, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 514, in _processConfig
    config[dpid][name]['balancer'].addSensorGroup(group_info)
KeyError: 'balancer'
]]>		</error>
	</testcase>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testSimpleBalance" time="0.001">
		<error message="'balancer'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/Simple_SciPass_balancer_only.xml" )
  File "./SciPass.py", line 50, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 514, in _processConfig
    config[dpid][name]['balancer'].addSensorGroup(group_info)
KeyError: 'balancer'
]]>		</error>
	</testcase>
</testsuite>
