<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20151117193054" tests="2" time="466.327">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="1.610"/>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testSimpleBalance" time="464.717">
		<failure message="4 != 8" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 201, in testSimpleBalance
    self.assertEquals(total_runs, 8)
AssertionError: 4 != 8
]]>		</failure>
	</testcase>
</testsuite>
