<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930150535" tests="1" time="0.022">
	<properties/>
	<system-out>
<![CDATA[0000000000000001R&Ejson
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.022">
		<error message="[Errno 2] No such file or directory: '0000000000000001R&amp;Ejson'" type="IOError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 28, in test_initial_config
    with open(self.file) as data_file:
IOError: [Errno 2] No such file or directory: '0000000000000001R&Ejson'

Stdout:
0000000000000001R&Ejson
]]>		</error>
	</testcase>
</testsuite>
