<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="2" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20151020144408" tests="2" time="3.741">
	<properties/>
	<system-out>
<![CDATA[1000
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="1.802">
		<failure message="1000 != 566" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 42, in testInit
    self.assertEquals(len(flows), 566)
AssertionError: 1000 != 566

Stdout:
1000
]]>		</failure>
	</testcase>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testSimpleBalance" time="1.939">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 104, in testSimpleBalance
    self.assertTrue( len(flows) == 566)
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
