<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="SimpleBalancerTest.TestPrefix-20151202164314" tests="10" time="0.033">
	<properties/>
	<system-out>
<![CDATA[None
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_add_sensor_prefix" time="0.001"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_del_sensor_prefix" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_get_largest_prefix" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_get_prefix_sensor" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_set_prefix_bw" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix_for_sensors" time="0.002"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix_for_sensors_large" time="0.027"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_sensor_prefix" time="0.001"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_move_sensor_prefix" time="0.001">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerTest.py", line 279, in test_move_sensor_prefix
    self.assertTrue(self.sensor == 1)
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
